config/routes.rb
Web::Application.routes.draw do

  root :to => 'pages#about'
  match 'pages/contact', :to => 'pages#contact'
  match 'pages/projects',   :to => 'pages#projects'
  match 'pages/about',   :to => 'pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
     @title = "About"
  end

  def projects
     @title = "Projects"
  end

  def contact
     @title = "Contact"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= stylesheet_link_tag '/stylesheets/bootstrap/css/bootstrap.min.css', :media => 'all' %>
<%= stylesheet_link_tag '/stylesheets/flexslider.css', :media => 'screen' %>
<%= stylesheet_link_tag '/stylesheets/custom.css', :media => 'screen' %>
<%= javascript_include_tag "jquery-1.9.1.min.js", "jquery.flexslider-min.js", "custom", "jquery.anchor.js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hyeyun Shin | <%= @title %></title>
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
  <meta name="description" content="Hyeyun Shin Personal Website">
  <meta name="keywords" content="Software Developer">
  <meta name="author" content="Hyeyun Shin">
  <meta charset="UTF-8">
</head>
<body>
  <a name="ontop" id="ontop"></a>
  <div class="container">  
  <div class="row">
  <div class="span10">
    <h1 class="title"><%= link_to "Hyeyun Shin", root_path, :class => "title" %>
    <% linkedin_icon = image_tag("/images/linkedin_icon.png", :alt => "linkedin", :size => "30x30" ) %>
    <%= link_to linkedin_icon, "http://ca.linkedin.com/pub/hyeyun-shin/29/251/b65/", :target => "_blank" %>
    <% googleplus_icon = image_tag("/images/googleplus_icon.png", :alt => "googleplus", :size => "30x30" ) %>
    <%= link_to googleplus_icon, "https://plus.google.com/u/0/118286447928746408208", :target => "_blank" %>
  </h1>
  </div>
  </div>
  <div class="row">
  <div class="span7">
    <p class="info">h3shin@uwaterloo.ca ▪ (226) 339-3578</p>
  </div>
  <div class="menu">
  <div class="span3">
  <nav class="round">
    <ul>
    <li><%= link_to "About", root_path %></li>
    <li><%= link_to "Blog", "http://hyeyunshin.blogspot.com", :target => "_blank" %></li>
    <li><%= link_to "Projects", pages_projects_path %></li>
  </ul>
  </div>  
  </div>
  </div>
  </div>
     <%= yield %>
  <div class="container">
  <div class="row">
  <div class="span10">
  <br>
  <p class="footer">hyeyunshin.com | May 2013</p>
  </div>
  </div>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
<div class="row">
<div class="span10">
<div class="flexslider">
  <ul class="slides">
    <li>
      <%= image_tag("/images/image1.jpg", :alt => "", :size => "950x300") %>
    </li>
    <li>
      <%= image_tag("/images/image2.jpg", :alt => "", :size => "950x300") %>
    </li>
    <li>
      <%= image_tag("/images/image3.jpg", :alt => "", :size => "950x300") %>
    </li>
    <li>
      <%= image_tag("/images/image4.jpg", :alt => "", :size => "950x300") %>
    </li>
  </ul>
</div>
</div>
</div>
</div>
<div class="body_part">
<div class="container">
<div class="row">
<div class="span10">

<p>Hi. I graduated from University of Waterloo, Waterloo,
Ontario with a BMath in Computer Science.<br>
I mainly worked as a C++ developer during my internships.</p>

<p>This is my personal website that I've built using Ruby on Rails.
Although Rails is meant for database-backed dynamic websites, I still had fun making this,
adding some dynamic contents here and there.
I think it was a good way to get a feel of it.
I'm planning to build a legit Ruby on Rails web application in near future to have a better feel.</p>

<p>I love programming and animals (especially dogs and llamas).</p>
<p><%= link_to "View Resume", "#", :class => "resume_title info", :id => "resume" %></p>
</div>
</div>
</div>
</div>
<div class="container">
<div class="row">
<div class="span10">
<div class="resume">
<p class="subtitle">Summary</p>

<p><b>▪ Programming</b>: C/C++, Java, Python,
Scheme, Shell script, Ruby, and SQL</p>

<p>▪ Solid problem solving skills with
strong mathematical and financial background</p>

<p>▪ Strong knowledge of
object-oriented programming and design patterns</p>

<p>▪ Solid understanding of various data structures and algorithms</p>

<p>▪ Communicate effectively across a wide range of audience</p>

<p>▪ Speak and write in French (intermediate) and Korean (proficient)</p>

<p>&nbsp;</p>

<p class="subtitle">Education</p>

<p><b>Bmath in Computer
Science Co-op</b></p>

<p>University of Waterloo, Waterloo, ON, September 2008 - April 2013</p>

<p>&nbsp;</p>
<p><b>Relevant Assignments:</b></p>

<p>▪ Developed an escape game on Android, designing puzzle UI and game logic (Software Design and Architecture)</p>

<p>▪ Implemented Go-Back-N protocol using Java to transfer data across unreliable network
(Computer Networks)</p>

<p>▪ Implemented processes, system calls, and virtual memory system in OS/161 kernel using C (Operating
Systems)</p>

<p>▪ Wrote a compiler
from a subset of C to MIPS in C++ (Sequential Programs)</p>

<p>&nbsp;</p>

<p><b>Diplome d'Etudes Collegiales</b>, Science</p>

<p>CEGEP John Abbott College, Sainte-Anne-de-Bellevue,
QC, 2006 - 2008</p>

<p>&nbsp;</p>

<p class="subtitle">Work Experience</p>

<p 
><b>Software Developer, OANDA </b> Toronto, ON, <i>04/12 - 08/12</i></p>

<p>▪ Coded in MQL4 to output daily
client-side performance report on trade delays for better analysis</p>

<p>▪ Developed new feature to limit
client connection rate at a constant time using performance monitor</p>

<p>▪ Analyzed log file and de-bugged
user input validation code on trade units and expiration date</p>

<p>▪ Developed automatic market
halting feature that automatically changes server configuration based on protobuf data</p>

<p><b>Technologies</b>: C++, Python, MQL4, Git</p>

<p>&nbsp;</p>

<p><b>C++ Developer, OANDA </b>Toronto, ON, <i>09/11 - 12/11</i></p>

<p>▪ Improved system efficiency by
multithreading start-up process of Customer Information System server</p>

<p>▪ Developed rebook functionality
that allows internal traders to rebook past trades</p>

<p>▪ Updated value date server code to
automatically adjust settlement date according to different time zones</p>

<p>▪ Worked closely with technical
leadership to understand business requirements</p>

<p><b>Technologies</b>: C++, SQL, DB2, Git</p>

<p>&nbsp;</p>

<p><b>Actuarial Co-op, Manulife </b>Kitchener, ON, <i>09/10 - 12/10</i></p>

<p>▪ Developed VBA macros that
automatically updates monthly manual reserves</p>

<p>▪ Performed AuG43 spot checking for
internal and external audit</p>

<p>▪ Performed reserve movement
analysis for various life insurance blocks of business</p>

<p>&nbsp;</p>

<p 
><b>Inforce Pricing Analyst, Manulife </b>Kitchener, ON, <i>01/10 - 04/10</i></p>

<p 
>▪ Generated new premium rates for
Expense Comp for policyholders at age over 65</p>

<p 
>▪ Updated cost of insurance rates
of universal life block to reflect improved mortality rates </p>

<p>&nbsp;</p>

<p class="subtitle">Activities and Interests</p>
<p><b>Machine Learning </b>(certificate
achieved), Coursera.org, <i>04/12 &#8211; 07/12 </i></p>
<p><b>Co-op Representative</b>, MathSoc, University of Waterloo, ON, <i>01/11 - 04/11</i></p>

<p 
><b>Construction Helper</b>, Habitat for Humanity, Waterloo, ON, <i>09/10</i></p>

<p 
><b>Student101 Volunteer</b>, University of Waterloo, Waterloo, ON, <i>07/10</i></p>

<p 
><b>Investopedia Stock Simulation
Competition</b>, WIREX, University of Waterloo,
Waterloo, ON, <i>01/09 - 04/09</i></p>

<p>▪ Ranked in top 10%</p>

<p>&nbsp;</p>

<p>Enjoy doodling, squash, and making jokes</p>
</div>
</div>
</div>
</div>
<div class="container">
<div class="row">
<div class="span10">
<div class="temp">
<% go_up_icon = image_tag( "/images/arrow_up.png", :alt => "Go up", :class => "go_up" ) %>
<%= link_to go_up_icon, "#ontop",  :class => "anchorLink" %>
</div>
</div>
</div>
</div>

app/views/pages/contact.html.erb
to be deleted

app/views/pages/projects.html.erb
<div class="container">
<div class="row">
<div class="span10">
<%= image_tag("/images/under_construction.jpg", :alt => "under construction", :class => "rad") %>
</div>
</div>
</div>